spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service:
  greeting: "AMBIENTE ALTERADO PARA TESTE DINAMICO"
  default-value: "PROD"
